### PR TITLE
Update base to centos and update installations

### PR DESCRIPTION
**Pull request by hazim1093**

### CODE REVIEW

**Comment by stakater-user** [comment]
@hazim1093 Yikes! You better fix it before anyone else finds out! [Build 1](https://jenkins.release.stakater.com/job/Stakater%20Docker/job/pipeline-tools/job/PR-8/1/) has Failed!

**Comment by stakater-user** [comment]
@hazim1093 Yikes! You better fix it before anyone else finds out! [Build 2](https://jenkins.release.stakater.com/job/Stakater%20Docker/job/pipeline-tools/job/PR-8/2/) has Failed!

**Comment by stakater-user** [comment]
@hazim1093 Yikes! You better fix it before anyone else finds out! [Build 3](https://jenkins.release.stakater.com/job/Stakater%20Docker/job/pipeline-tools/job/PR-8/3/) has Failed!

**Comment by stakater-user** [comment]
@hazim1093 Yikes! You better fix it before anyone else finds out! [Build 4](https://jenkins.release.stakater.com/job/Stakater%20Docker/job/pipeline-tools/job/PR-8/4/) has Failed!

**Comment by stakater-user** [comment]
@hazim1093 Yikes! You better fix it before anyone else finds out! [Build 5](https://jenkins.release.stakater.com/job/Stakater%20Docker/job/pipeline-tools/job/PR-8/5/) has Failed!

**Comment by stakater-user** [comment]
@hazim1093 Yikes! You better fix it before anyone else finds out! [Build 6](https://jenkins.release.stakater.com/job/Stakater%20Docker/job/pipeline-tools/job/PR-8/6/) has Failed!

**Comment by stakater-user** [comment]
@hazim1093 Yikes! You better fix it before anyone else finds out! [Build 7](https://jenkins.release.stakater.com/job/Stakater%20Docker/job/pipeline-tools/job/PR-8/7/) has Failed!

**Comment by stakater-user** [comment]
@hazim1093 Yikes! You better fix it before anyone else finds out! [Build 8](https://jenkins.release.stakater.com/job/Stakater%20Docker/job/pipeline-tools/job/PR-8/8/) has Failed!

**Comment by stakater-user** [comment]
@hazim1093 Yikes! You better fix it before anyone else finds out! [Build 9](https://jenkins.release.stakater.com/job/Stakater%20Docker/job/pipeline-tools/job/PR-8/9/) has Failed!

**Comment by stakater-user** [comment]
@hazim1093 Image is available for testing. `docker pull docker.io/stakater/pipeline-tools:SNAPSHOT-PR-8-10`

**Comment by stakater-user** [comment]
@hazim1093 Image is available for testing. `docker pull docker.io/stakater/pipeline-tools:SNAPSHOT-PR-8-11`

**Comment by stakater-user** [comment]
@hazim1093 Image is available for testing. `docker pull docker.io/stakater/pipeline-tools:SNAPSHOT-PR-8-12`

**Comment by stakater-user** [comment]
@hazim1093 Image is available for testing. `docker pull docker.io/stakater/pipeline-tools:SNAPSHOT-PR-8-13`

**Review by rasheedamir — APPROVED** [review]
Approved with threats (haha)

**Pull request merged**
