### PR TITLE
upgrade helm to 2.11

### PR DESCRIPTION
**Pull request by kahootali**

### CODE REVIEW

**Comment by stakater-user** [comment]
@kahootali Yikes! You better fix it before anyone else finds out! [Build 1](https://jenkins.release.stakater.com/job/Stakater%20Docker/job/pipeline-tools/job/PR-5/1/) has Failed!

**Comment by stakater-user** [comment]
@kahootali Yikes! You better fix it before anyone else finds out! [Build 2](https://jenkins.release.stakater.com/job/Stakater%20Docker/job/pipeline-tools/job/PR-5/2/) has Failed!

**Comment by stakater-user** [comment]
@kahootali Image is available for testing. `docker pull docker.io/stakater/pipeline-tools:SNAPSHOT-PR-5-4`

**Comment by stakater-user** [comment]
@kahootali Yikes! You better fix it before anyone else finds out! [Build 5](https://jenkins.release.stakater.com/job/Stakater%20Docker/job/pipeline-tools/job/PR-5/5/) has Failed!

**Comment by stakater-user** [comment]
@kahootali Yikes! You better fix it before anyone else finds out! [Build 7](https://jenkins.release.stakater.com/job/Stakater%20Docker/job/pipeline-tools/job/PR-5/7/) has Failed!

**Comment by stakater-user** [comment]
@kahootali Image is available for testing. `docker pull docker.release.stakater.com:443/stakater/pipeline-tools:SNAPSHOT-PR-5-9`

**Review by ahsan-storm — APPROVED** [review]

**Pull request merged**
